# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/showRoom.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os,sys
sys.path.append(os.path.join(sys.path[0], "../backend"))
from room import viewKamar

class RoomPage(QtWidgets.QMainWindow):
    def __init__(self, window, parent=None, parent2=None):
        super(RoomPage, self).__init__(parent)
        self.MainWindow = window
        self.data = viewKamar(["","",""])
        remains = 9 - len(self.data) % 9
        for _ in range(remains):
            self.data.append(('','',''))
        self.Page = 0
        self.MaxPage = len(self.data)
        self.Parent = parent
        self.Parent2 = parent2

    def toLoginPage(self):
        self.Parent.setupUi(self.MainWindow)
        self.MainWindow.show()

    def toAppointmentPage(self):
        self.Parent2.setupUi(self.MainWindow)
        self.MainWindow.show()

    def nextPageFunction(self):
        if self.Page + 9 < self.MaxPage:
            self.Page += 9
        self.findRoom()

    def prevPageFunction(self):
        if self.Page - 9 >= 0:
            self.Page -= 9
        self.findRoom()
        
    def checkString(self, string):
        if string != '':
            return True
        else:
            return False

    def updateRoom(self):
        query = self.searchQuery.toPlainText()
        query = query.split(";")
        if query[0] != "":
            query[0] = int(query[0])
        self.data = viewKamar([query[0],query[1],query[2]])
        remains = 9 - len(self.data) % 9
        for _ in range(remains):
            self.data.append(('','',''))
        self.findRoom()

    def findRoom(self):
        _translate = QtCore.QCoreApplication.translate
        data = self.data

        if (self.checkString(data[self.Page][0])):
            self.roomId1.setText(data[self.Page][0])
            self.roomPrice1.setText("IDR " + str(data[self.Page][2]))
            self.roomType1.setText("Room Type " + str(data[self.Page][1]))
            self.card1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        else:
            self.roomId1.setText("")
            self.roomPrice1.setText("")
            self.roomType1.setText("")
            self.card1.setText("")
        
        if (self.checkString(data[self.Page + 1][0])):
            self.roomId2.setText(data[self.Page + 1][0])
            self.roomPrice2.setText("IDR " + str(data[self.Page + 1][2]))
            self.roomType2.setText("Room Type " + str(data[self.Page + 1][1]))
            self.card2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        else:
            self.roomId2.setText("")
            self.roomPrice2.setText("")
            self.roomType2.setText("")
            self.card2.setText("")

        if (self.checkString(data[self.Page + 2][0])):
            self.roomId3.setText(data[self.Page + 2][0])
            self.roomPrice3.setText("IDR "+ str(data[self.Page + 2][2]))
            self.roomType3.setText("Room Type " + str(data[self.Page + 2][1]))
            self.card3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        else:
            self.roomId3.setText("")
            self.roomPrice3.setText("")
            self.roomType3.setText("")
            self.card3.setText("")

        if (self.checkString(data[self.Page + 3][0])):
            self.roomId4.setText(data[self.Page + 3][0])
            self.roomPrice4.setText("IDR "+ str(data[self.Page + 3][2]))
            self.roomType4.setText("Room Type " + str(data[self.Page + 3][1]))
            self.card4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        else:
            self.roomId4.setText("")
            self.roomPrice4.setText("")
            self.roomType4.setText("")
            self.card4.setText("")

        if (self.checkString(data[self.Page + 4][0])):
            self.roomId5.setText(data[self.Page + 4][0])
            self.roomPrice5.setText("IDR " + str(data[self.Page + 4][2]))
            self.roomType5.setText("Room Type " + str(data[self.Page + 4][1]))
            self.card5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        else:
            self.roomId5.setText("")
            self.roomPrice5.setText("")
            self.roomType5.setText("")
            self.card5.setText("")

        if (self.checkString(data[self.Page + 5][0])):
            self.roomId6.setText(data[self.Page + 5][0])
            self.roomPrice6.setText("IDR "+str(data[self.Page + 5][2]))
            self.roomType6.setText("Room Type " + str(data[self.Page + 5][1]))
            self.card6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        else:
            self.roomId6.setText("")
            self.roomPrice6.setText("")
            self.roomType6.setText("")
            self.card6.setText("")

        if (self.checkString(data[self.Page + 6][0])):
            self.roomId7.setText(data[self.Page + 6][0])
            self.roomPrice7.setText("IDR "+str(data[self.Page + 6][2]))
            self.roomType7.setText("Room Type " + str(data[self.Page + 6][1]))
            self.card7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        else:
            self.roomId7.setText("")
            self.roomPrice7.setText("")
            self.roomType7.setText("")
            self.card7.setText("")

        if (self.checkString(data[self.Page + 7][0])):
            self.roomId8.setText(data[self.Page + 7][0])
            self.roomPrice8.setText("IDR "+str(data[self.Page + 7][2]))
            self.roomType8.setText("Room Type " + str(data[self.Page + 7][1]))
            self.card8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        else:
            self.roomId8.setText("")
            self.roomPrice8.setText("")
            self.roomType8.setText("")
            self.card8.setText("")

        if (self.checkString(data[self.Page + 8][0])):
            self.roomId9.setText(data[self.Page + 8][0])
            self.roomPrice9.setText("IDR "+str(data[self.Page + 8][2]))
            self.roomType9.setText("Room Type " + str(data[self.Page + 8][1]))
            self.card9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        else:
            self.roomId9.setText("")
            self.roomPrice9.setText("")
            self.roomType9.setText("")
            self.card9.setText("")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 630)
        MainWindow.setMinimumSize(QtCore.QSize(1120, 630))
        MainWindow.setMaximumSize(QtCore.QSize(1120, 630))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-10, -10, 211, 671))
        self.frame_2.setStyleSheet("background-color: white;\n"
"border: 0px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 161, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setStyleSheet("text-align:center;\n"
"color: rgb(106, 110, 131);\n"
"font: 25px;\n"
"font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setStyleSheet("text-align:center;\n"
"color: #1CA8FF;\n"
"font: 25px;\n"
"font-weight: bold;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 100, 131, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.label_8.setStyleSheet("text-align:left;\n"
"color: rgb(106, 110, 131);\n"
"font: 15px;\n"
"font-weight: bold;")
        self.label_8.setObjectName("label_8")
        self.label_8.clicked.connect(self.toAppointmentPage)
        self.horizontalLayout_3.addWidget(self.label_8)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 180, 131, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_9.setStyleSheet("text-align:center;\n"
"color: rgb(28, 168, 255);\n"
"font: 15px;\n"
"font-weight: bold;")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.signOutButton = QtWidgets.QPushButton(self.frame_2)
        self.signOutButton.setGeometry(QtCore.QRect(50, 570, 100, 40))
        self.signOutButton.setMinimumSize(QtCore.QSize(100, 40))
        self.signOutButton.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.signOutButton.setFont(font)
        self.signOutButton.setStyleSheet("""
        QPushButton {
            background-color: rgb(28, 168, 255);\n
            color: white;
            border: 0px;
            border-radius: 10px;
            padding: 10px;
        }
        QPushButton:hover {
            color: rgb(28, 168, 255);
            background-color: white;
        }
        """)
        self.signOutButton.setObjectName("signOutButton")
        self.signOutButton.clicked.connect(self.toLoginPage)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(230, 90, 861, 509))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_9.setMinimumSize(QtCore.QSize(269, 161))
        self.frame_9.setMaximumSize(QtCore.QSize(269, 161))
        self.frame_9.setStyleSheet("background-color: #FFFFFF;\n"
"border-radius: 20px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.frame_9)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(0, 20, 271, 141))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem3 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem3)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.roomId7 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomId7.setFont(font)
        self.roomId7.setStyleSheet("color : black;\n"
"font-size: 25px;\n"
"")
        self.roomId7.setObjectName("roomId7")
        self.verticalLayout_32.addWidget(self.roomId7)
        self.horizontalLayout_22.addLayout(self.verticalLayout_32)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem4)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.roomType7 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.roomType7.setFont(font)
        self.roomType7.setStyleSheet("color : #6A6E83;")
        self.roomType7.setObjectName("roomType7")
        self.verticalLayout_33.addWidget(self.roomType7)
        self.roomPrice7 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomPrice7.setFont(font)
        self.roomPrice7.setStyleSheet("color : black;\n"
"font-size: 20px;")
        self.roomPrice7.setObjectName("roomPrice7")
        self.verticalLayout_33.addWidget(self.roomPrice7)
        self.horizontalLayout_22.addLayout(self.verticalLayout_33)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem5)
        self.verticalLayout_31.addLayout(self.horizontalLayout_22)
        self.card7 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.card7.setFont(font)
        self.card7.setStyleSheet("color : #1CA8FF;\n"
"font-size: 15px;")
        self.card7.setObjectName("card7")
        self.verticalLayout_31.addWidget(self.card7)
        self.gridLayout.addWidget(self.frame_9, 4, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_10.setMinimumSize(QtCore.QSize(269, 161))
        self.frame_10.setMaximumSize(QtCore.QSize(269, 161))
        self.frame_10.setStyleSheet("background-color: #FFFFFF;\n"
"border-radius: 20px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.frame_10)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(0, 20, 271, 141))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem6 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem6)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.roomId8 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomId8.setFont(font)
        self.roomId8.setStyleSheet("color : black;\n"
"font-size: 25px;\n"
"")
        self.roomId8.setObjectName("roomId8")
        self.verticalLayout_35.addWidget(self.roomId8)
        self.horizontalLayout_23.addLayout(self.verticalLayout_35)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem7)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.roomType8 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.roomType8.setFont(font)
        self.roomType8.setStyleSheet("color : #6A6E83;")
        self.roomType8.setObjectName("roomType8")
        self.verticalLayout_36.addWidget(self.roomType8)
        self.roomPrice8 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomPrice8.setFont(font)
        self.roomPrice8.setStyleSheet("color : black;\n"
"font-size: 20px;")
        self.roomPrice8.setObjectName("roomPrice8")
        self.verticalLayout_36.addWidget(self.roomPrice8)
        self.horizontalLayout_23.addLayout(self.verticalLayout_36)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem8)
        self.verticalLayout_34.addLayout(self.horizontalLayout_23)
        self.card8 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.card8.setFont(font)
        self.card8.setStyleSheet("color : #1CA8FF;\n"
"font-size: 15px;")
        self.card8.setObjectName("card8")
        self.verticalLayout_34.addWidget(self.card8)
        self.gridLayout.addWidget(self.frame_10, 4, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 0, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_6.setMinimumSize(QtCore.QSize(269, 161))
        self.frame_6.setMaximumSize(QtCore.QSize(269, 161))
        self.frame_6.setStyleSheet("background-color: #FFFFFF;\n"
"border-radius: 20px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.frame_6)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(0, 20, 271, 141))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem10 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem10)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.roomId4 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomId4.setFont(font)
        self.roomId4.setStyleSheet("color : black;\n"
"font-size: 25px;\n"
"")
        self.roomId4.setObjectName("roomId4")
        self.verticalLayout_23.addWidget(self.roomId4)
        self.horizontalLayout_19.addLayout(self.verticalLayout_23)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem11)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.roomType4 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.roomType4.setFont(font)
        self.roomType4.setStyleSheet("color : #6A6E83;")
        self.roomType4.setObjectName("roomType4")
        self.verticalLayout_24.addWidget(self.roomType4)
        self.roomPrice4 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomPrice4.setFont(font)
        self.roomPrice4.setStyleSheet("color : black;\n"
"font-size: 20px;")
        self.roomPrice4.setObjectName("roomPrice4")
        self.verticalLayout_24.addWidget(self.roomPrice4)
        self.horizontalLayout_19.addLayout(self.verticalLayout_24)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem12)
        self.verticalLayout_22.addLayout(self.horizontalLayout_19)
        self.card4 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.card4.setFont(font)
        self.card4.setStyleSheet("color : #1CA8FF;\n"
"font-size: 15px;")
        self.card4.setObjectName("card4")
        self.verticalLayout_22.addWidget(self.card4)
        self.gridLayout.addWidget(self.frame_6, 2, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_8.setMinimumSize(QtCore.QSize(269, 161))
        self.frame_8.setMaximumSize(QtCore.QSize(269, 161))
        self.frame_8.setStyleSheet("background-color: #FFFFFF;\n"
"border-radius: 20px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.frame_8)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(0, 20, 271, 141))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem13 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem13)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.roomId6 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomId6.setFont(font)
        self.roomId6.setStyleSheet("color : black;\n"
"font-size: 25px;\n"
"")
        self.roomId6.setObjectName("roomId6")
        self.verticalLayout_29.addWidget(self.roomId6)
        self.horizontalLayout_21.addLayout(self.verticalLayout_29)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem14)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.roomType6 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.roomType6.setFont(font)
        self.roomType6.setStyleSheet("color : #6A6E83;")
        self.roomType6.setObjectName("roomType6")
        self.verticalLayout_30.addWidget(self.roomType6)
        self.roomPrice6 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomPrice6.setFont(font)
        self.roomPrice6.setStyleSheet("color : black;\n"
"font-size: 20px;")
        self.roomPrice6.setObjectName("roomPrice6")
        self.verticalLayout_30.addWidget(self.roomPrice6)
        self.horizontalLayout_21.addLayout(self.verticalLayout_30)
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem15)
        self.verticalLayout_28.addLayout(self.horizontalLayout_21)
        self.card6 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.card6.setFont(font)
        self.card6.setStyleSheet("color : #1CA8FF;\n"
"font-size: 15px;")
        self.card6.setObjectName("card6")
        self.verticalLayout_28.addWidget(self.card6)
        self.gridLayout.addWidget(self.frame_8, 2, 4, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_3.setMinimumSize(QtCore.QSize(269, 161))
        self.frame_3.setMaximumSize(QtCore.QSize(269, 161))
        self.frame_3.setStyleSheet("background-color: #FFFFFF;\n"
"border-radius: 20px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 20, 271, 141))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem16 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem16)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.roomId1 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomId1.setFont(font)
        self.roomId1.setStyleSheet("color : black;\n"
"font-size: 25px;\n"
"")
        self.roomId1.setObjectName("roomId1")
        self.verticalLayout_40.addWidget(self.roomId1)
        self.horizontalLayout_16.addLayout(self.verticalLayout_40)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem17)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.roomType1 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.roomType1.setFont(font)
        self.roomType1.setStyleSheet("color : #6A6E83;")
        self.roomType1.setObjectName("roomType1")
        self.verticalLayout_15.addWidget(self.roomType1)
        self.roomPrice1 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomPrice1.setFont(font)
        self.roomPrice1.setStyleSheet("color : black;\n"
"font-size: 20px;")
        self.roomPrice1.setObjectName("roomPrice1")
        self.verticalLayout_15.addWidget(self.roomPrice1)
        self.horizontalLayout_16.addLayout(self.verticalLayout_15)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem18)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.card1 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.card1.setFont(font)
        self.card1.setStyleSheet("color : #1CA8FF;\n"
"font-size: 15px;")
        self.card1.setObjectName("card1")
        self.verticalLayout_13.addWidget(self.card1)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_7.setMinimumSize(QtCore.QSize(269, 161))
        self.frame_7.setMaximumSize(QtCore.QSize(269, 161))
        self.frame_7.setStyleSheet("background-color: #FFFFFF;\n"
"border-radius: 20px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.frame_7)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(0, 20, 271, 141))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem19 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem19)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.roomId5 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomId5.setFont(font)
        self.roomId5.setStyleSheet("color : black;\n"
"font-size: 25px;\n"
"")
        self.roomId5.setObjectName("roomId5")
        self.verticalLayout_26.addWidget(self.roomId5)
        self.horizontalLayout_20.addLayout(self.verticalLayout_26)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem20)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.roomType5 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.roomType5.setFont(font)
        self.roomType5.setStyleSheet("color : #6A6E83;")
        self.roomType5.setObjectName("roomType5")
        self.verticalLayout_27.addWidget(self.roomType5)
        self.roomPrice5 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomPrice5.setFont(font)
        self.roomPrice5.setStyleSheet("color : black;\n"
"font-size: 20px;")
        self.roomPrice5.setObjectName("roomPrice5")
        self.verticalLayout_27.addWidget(self.roomPrice5)
        self.horizontalLayout_20.addLayout(self.verticalLayout_27)
        spacerItem21 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem21)
        self.verticalLayout_25.addLayout(self.horizontalLayout_20)
        self.card5 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.card5.setFont(font)
        self.card5.setStyleSheet("color : #1CA8FF;\n"
"font-size: 15px;")
        self.card5.setObjectName("card5")
        self.verticalLayout_25.addWidget(self.card5)
        self.gridLayout.addWidget(self.frame_7, 2, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem22, 3, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_11.setMinimumSize(QtCore.QSize(269, 161))
        self.frame_11.setMaximumSize(QtCore.QSize(269, 161))
        self.frame_11.setStyleSheet("background-color: #FFFFFF;\n"
"border-radius: 20px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.frame_11)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(0, 20, 271, 141))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem23 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem23)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.roomId9 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomId9.setFont(font)
        self.roomId9.setStyleSheet("color : black;\n"
"font-size: 25px;\n"
"")
        self.roomId9.setObjectName("roomId9")
        self.verticalLayout_38.addWidget(self.roomId9)
        self.horizontalLayout_24.addLayout(self.verticalLayout_38)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem24)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.roomType9 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.roomType9.setFont(font)
        self.roomType9.setStyleSheet("color : #6A6E83;")
        self.roomType9.setObjectName("roomType9")
        self.verticalLayout_39.addWidget(self.roomType9)
        self.roomPrice9 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomPrice9.setFont(font)
        self.roomPrice9.setStyleSheet("color : black;\n"
"font-size: 20px;")
        self.roomPrice9.setObjectName("roomPrice9")
        self.verticalLayout_39.addWidget(self.roomPrice9)
        self.horizontalLayout_24.addLayout(self.verticalLayout_39)
        spacerItem25 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem25)
        self.verticalLayout_37.addLayout(self.horizontalLayout_24)
        self.card9 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.card9.setFont(font)
        self.card9.setStyleSheet("color : #1CA8FF;\n"
"font-size: 15px;")
        self.card9.setObjectName("card9")
        self.verticalLayout_37.addWidget(self.card9)
        self.gridLayout.addWidget(self.frame_11, 4, 4, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_5.setMinimumSize(QtCore.QSize(269, 161))
        self.frame_5.setMaximumSize(QtCore.QSize(269, 161))
        self.frame_5.setStyleSheet("background-color: #FFFFFF;\n"
"border-radius: 20px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.frame_5)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(0, 20, 271, 141))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem26 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem26)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.roomId3 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomId3.setFont(font)
        self.roomId3.setStyleSheet("color : black;\n"
"font-size: 25px;\n"
"")
        self.roomId3.setObjectName("roomId3")
        self.verticalLayout_20.addWidget(self.roomId3)
        self.horizontalLayout_18.addLayout(self.verticalLayout_20)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem27)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.roomType3 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.roomType3.setFont(font)
        self.roomType3.setStyleSheet("color : #6A6E83;")
        self.roomType3.setObjectName("roomType3")
        self.verticalLayout_21.addWidget(self.roomType3)
        self.roomPrice3 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomPrice3.setFont(font)
        self.roomPrice3.setStyleSheet("color : black;\n"
"font-size: 20px;")
        self.roomPrice3.setObjectName("roomPrice3")
        self.verticalLayout_21.addWidget(self.roomPrice3)
        self.horizontalLayout_18.addLayout(self.verticalLayout_21)
        spacerItem28 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem28)
        self.verticalLayout_19.addLayout(self.horizontalLayout_18)
        self.card3 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.card3.setFont(font)
        self.card3.setStyleSheet("color : #1CA8FF;\n"
"font-size: 15px;")
        self.card3.setObjectName("card3")
        self.verticalLayout_19.addWidget(self.card3)
        self.gridLayout.addWidget(self.frame_5, 0, 4, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_4.setMinimumSize(QtCore.QSize(269, 161))
        self.frame_4.setMaximumSize(QtCore.QSize(269, 161))
        self.frame_4.setStyleSheet("background-color: #FFFFFF;\n"
"border-radius: 20px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(0, 20, 271, 141))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem29 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem29)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_17.addLayout(self.verticalLayout_17)
        self.roomId2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomId2.setFont(font)
        self.roomId2.setStyleSheet("color : black;\n"
"font-size: 25px;\n"
"")
        self.roomId2.setObjectName("roomId2")
        self.horizontalLayout_17.addWidget(self.roomId2)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem30)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.roomType2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.roomType2.setFont(font)
        self.roomType2.setStyleSheet("color : #6A6E83;")
        self.roomType2.setObjectName("roomType2")
        self.verticalLayout_18.addWidget(self.roomType2)
        self.roomPrice2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.roomPrice2.setFont(font)
        self.roomPrice2.setStyleSheet("color : black;\n"
"font-size: 20px;")
        self.roomPrice2.setObjectName("roomPrice2")
        self.verticalLayout_18.addWidget(self.roomPrice2)
        self.horizontalLayout_17.addLayout(self.verticalLayout_18)
        spacerItem31 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem31)
        self.verticalLayout_16.addLayout(self.horizontalLayout_17)
        self.card2 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.card2.setFont(font)
        self.card2.setStyleSheet("color : #1CA8FF;\n"
"font-size: 15px;")
        self.card2.setObjectName("card2")
        self.verticalLayout_16.addWidget(self.card2)
        self.gridLayout.addWidget(self.frame_4, 0, 2, 1, 1)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(230, 10, 591, 81))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.searchQuery = QtWidgets.QTextEdit(self.horizontalLayoutWidget_10)
        self.searchQuery.setMinimumSize(QtCore.QSize(400, 41))
        self.searchQuery.setMaximumSize(QtCore.QSize(400, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.searchQuery.setFont(font)
        self.searchQuery.setStyleSheet("background-color: #FFFFFF;\n"
"border-radius: 20px;\n"
"border: 0px;\n"
"color: #c4c4c4;\n"
"text-align: center;\n"
"padding-top: 8px;")
        self.searchQuery.setObjectName("searchQuery")
        self.searchQuery.setPlaceholderText("Search by Room Type;Check in Date;Check Out Date")
        self.horizontalLayout_15.addWidget(self.searchQuery)
        self.findRoomButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.findRoomButton.setMinimumSize(QtCore.QSize(100, 40))
        self.findRoomButton.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.findRoomButton.setFont(font)
        self.findRoomButton.setStyleSheet("""
        QPushButton {
            background-color: rgb(28, 168, 255);\n
            color: white;
            border: 0px;
            border-radius: 10px;
        }
        QPushButton:hover {
            color: rgb(28, 168, 255);
            background-color: white;
        }
        """)
        self.findRoomButton.setObjectName("findRoomButton")
        self.findRoomButton.clicked.connect(self.updateRoom)
        self.horizontalLayout_15.addWidget(self.findRoomButton)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem32)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_16.setMinimumSize(QtCore.QSize(550, 0))
        self.label_16.setMaximumSize(QtCore.QSize(550, 16777215))
        self.label_16.setStyleSheet("color : #6A6E83;")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(910, 20, 168, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.prevPage = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.prevPage.setMinimumSize(QtCore.QSize(0, 30))
        self.prevPage.setStyleSheet("""
        QPushButton {
            background-color: rgb(28, 168, 255);\n
            color: white;
            border: 0px;
            border-radius: 10px;
            padding: 10px;
        }
        QPushButton:hover {
            color: rgb(28, 168, 255);
            background-color: white;
        }
        """)
        self.prevPage.setObjectName("prevPage")
        self.prevPage.clicked.connect(self.prevPageFunction)
        self.horizontalLayout_5.addWidget(self.prevPage)
        self.nextPage = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.nextPage.setMinimumSize(QtCore.QSize(0, 30))
        self.nextPage.setStyleSheet("""
        QPushButton {
            background-color: rgb(28, 168, 255);\n
            color: white;
            border: 0px;
            border-radius: 10px;
            padding: 10px;
        }
        QPushButton:hover {
            color: rgb(28, 168, 255);
            background-color: white;
        }
        """)
        self.nextPage.setObjectName("nextPage")
        self.nextPage.clicked.connect(self.nextPageFunction)
        self.horizontalLayout_5.addWidget(self.nextPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Hospita"))
        self.label_5.setText(_translate("MainWindow", "Lite"))
        self.label_8.setText(_translate("MainWindow", "Appointment"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Room</span></p></body></html>"))
        self.signOutButton.setText(_translate("MainWindow", "Sign Out"))
        self.roomId7.setText(_translate("MainWindow", self.data[self.Page + 6][0]))
        self.roomType7.setText(_translate("MainWindow", "Room Type " + str(self.data[self.Page + 6][1])))
        self.roomPrice7.setText(_translate("MainWindow", "IDR " + str(self.data[self.Page + 6][2])))
        self.card7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        self.roomId8.setText(_translate("MainWindow", self.data[self.Page + 7][0]))
        self.roomType8.setText(_translate("MainWindow", "Room Type " + str(self.data[self.Page + 7][1])))
        self.roomPrice8.setText(_translate("MainWindow", "IDR " + str(self.data[self.Page + 7][2])))
        self.card8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        self.roomId4.setText(_translate("MainWindow", self.data[self.Page + 3][0]))
        self.roomType4.setText(_translate("MainWindow", "Room Type " + str(self.data[self.Page + 3][1])))
        self.roomPrice4.setText(_translate("MainWindow", "IDR " + str(self.data[self.Page + 3][2])))
        self.card4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        self.roomId6.setText(_translate("MainWindow", self.data[self.Page + 5][0]))
        self.roomType6.setText(_translate("MainWindow", "Room Type " + str(self.data[self.Page + 5][1])))
        self.roomPrice6.setText(_translate("MainWindow", "IDR " + str(self.data[self.Page + 5][2])))
        self.card6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        self.roomId1.setText(_translate("MainWindow", self.data[self.Page][0]))
        self.roomType1.setText(_translate("MainWindow", "Room Type " + str(self.data[self.Page][1])))
        self.roomPrice1.setText(_translate("MainWindow", "IDR " + str(self.data[self.Page][2])))
        self.card1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        self.roomId5.setText(_translate("MainWindow", self.data[self.Page + 4][0]))
        self.roomType5.setText(_translate("MainWindow", "Room Type " + str(self.data[self.Page + 4][1])))
        self.roomPrice5.setText(_translate("MainWindow", "IDR " + str(self.data[self.Page + 4][2])))
        self.card5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        self.roomId9.setText(_translate("MainWindow", self.data[self.Page + 8][0]))
        self.roomType9.setText(_translate("MainWindow", "Room Type " + str(self.data[self.Page + 8][1])))
        self.roomPrice9.setText(_translate("MainWindow", "IDR " + str(self.data[self.Page + 8][2])))
        self.card9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        self.roomId3.setText(_translate("MainWindow", self.data[self.Page + 2][0]))
        self.roomType3.setText(_translate("MainWindow", "Room Type " + str(self.data[self.Page + 2][1])))
        self.roomPrice3.setText(_translate("MainWindow", "IDR " + str(self.data[self.Page + 2][2])))
        self.card3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        self.roomId2.setText(_translate("MainWindow", self.data[self.Page + 1][0]))
        self.roomType2.setText(_translate("MainWindow", "Room Type " + str(self.data[self.Page + 1][1])))
        self.roomPrice2.setText(_translate("MainWindow", "IDR " + str(self.data[self.Page + 1][2])))
        self.card2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Book Now</span></p></body></html>"))
        self.searchQuery.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>"))
        self.findRoomButton.setText(_translate("MainWindow", "Find Room"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Query Example: &quot;1;2022-12-08;2022-12-12&quot;, or &quot;3;;&quot;, or &quot;;2022-12-08;2022-12-12&quot;</span></p></body></html>"))
        self.prevPage.setText(_translate("MainWindow", "<"))
        self.nextPage.setText(_translate("MainWindow", ">"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = RoomPage()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
